# Generated by Django 3.0.5 on 2020-04-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'url',
                'managed': False,
            },
        ),
    ]
